### ISSUE TITLE
Fail to parse Crossref Schema.

### ISSUE THREAD

**Issue by fabiobatalha** [fabiobatalha/lxml_jats_crossref#1]
parsing JATS
parsing crossref
Traceback (most recent call last):
  File "parse_jats_xsd.py", line 12, in <module>
    schema = etree.XMLSchema(schema_root)
  File "src/lxml/xmlschema.pxi", line 87, in lxml.etree.XMLSchema.__init__ (src/lxml/lxml.etree.c:196366)
lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}element', attribute 'ref': The QName value '{http://www.ncbi.nlm.nih.gov/JATS1}abstract' does not resolve to a(n) element declaration., line 448

**Comment by ajrbyers** [comment]
Also seeing this exact issue wuth a newer version of crossref schemas.
